Reformatted the csv files and plotting notebooks
kdund/dd_limit_plot pull request #10
Opened 2023-10-27 01:08 UTC by yuema137

Thanks Knut for this helpful tool! I noticed that the files are in different format so I reformatted all of them into csv. Also I added a jupyter notebook to:
-  search for existing limit by name
-  make quick plots based on csv files

An example plot is attached below:
![image](https://github.com/kdund/dd_limit_plot/assets/44444818/ae0bd135-9fa9-49ee-bcb9-2e6bc8ff9e95)

2023-10-30 18:48 UTC, kdund requested changes
Hi, @yuema135, thanks a lot! 
I propose you go through and fix the header and then we can merge-- after that,I plan on doing some filename renaming and start thinking about the separate-metadata-yaml file :)

2023-10-30 18:48 UTC, kdund commented on data/CRESST2_SI_2016.csv
I think as a general matter the .csv parsers can deal with extra spaces? Better then to let them than to impose a very strict standard?

2023-10-30 18:48 UTC, kdund commented on data/PandaX-4T_2107.13438_SI_WIMP.csv
The header here was distorted

2023-10-30 18:48 UTC, kdund commented on data/xenon1t_1ty.csv
Also here the header was distorted by the conversion

2023-10-31 19:12 UTC, kdund commented on data/xenon1t_1ty.csv
> +"#,XENON,Collaboration,2018.,arXiv-1805.12562,Phys.,Rev.,Lett.,121,111302,",,
Adding commas at the end of a line messes up some .csv parsers-- best not to IMO

2024-02-28 20:50 UTC, kdund commented
Hi, @yuema137 do you think we close this one since the ideas were used for the limit reformatting we did?

2024-02-29 05:16 UTC, yuema137 commented
@kdund I fully agree with closing this! Thanks for doing the formatting (I know it's a pain...)

2024-02-29 05:16 UTC, closed without merging